server:
  port: 8001

# 服务别名---zookeeper注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 172.25.16.1:2181
      max-retries: 10
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.17.2.112:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123