server:
  port: 8001

spring:
  application:
    name: consul-consumer-order-hystrix

eureka:
  instance:
    hostname: localhost   #eureka服务端的实例名称 单机
  #    hostname: eureka7001.com   #eureka服务端的实例名称 集群
  client:
    register-with-eureka: true   #false表示不向注册中心注册自己
    fetch-registry: true   #false表示自己端就是注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/   #单机

feign:
  hystrix:
    enabled: true